# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = susynt-ss3l
PACKAGE_PRELOAD  = Tree
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = -lPyROOT -lXMLParser -lEG
PACKAGE_DEP      = SusyNtuple
PACKAGE_NOOPT    = 0

include $(ROOTCOREDIR)/Makefile-common
